project_name: demo-guestbook

builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - "8"

dockers:
- goos: linux
  goarch: amd64
  use: buildx
  dockerfile: Dockerfile
  image_templates:
    - "docker.io/twdps/{{ .ProjectName }}:{{ .Version }}-linux-amd64"
    - "docker.io/twdps/{{ .ProjectName }}:latest-linux-amd64"
  build_flag_templates:
    - --platform=linux/amd64
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/ThoughtWorks-DPS/{{ .ProjectName }}
    - --label=org.opencontainers.image.source=https://github.com/ThoughtWorks-DPS/{{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.licenses=MIT

- goos: linux
  goarch: arm64
  use: buildx
  dockerfile: Dockerfile
  image_templates:
    - "docker.io/twdps/{{ .ProjectName }}:{{ .Version }}-linux-arm64"
    - "docker.io/twdps/{{ .ProjectName }}:latest-linux-arm64"
  build_flag_templates:
    - --platform=linux/arm64/v8
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.description={{ .ProjectName }}
    - --label=org.opencontainers.image.url=https://github.com/ThoughtWorks-DPS/{{ .ProjectName }}
    - --label=org.opencontainers.image.source=https://github.com/ThoughtWorks-DPS/{{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.licenses=MIT

docker_manifests:
  - name_template: docker.io/twdps/{{ .ProjectName }}:{{ .Version }}
    image_templates:
    - docker.io/twdps/{{ .ProjectName }}:{{ .Version }}-linux-amd64
    - docker.io/twdps/{{ .ProjectName }}:{{ .Version }}-linux-arm64
  - name_template: docker.io/twdps/{{ .ProjectName }}:latest
    image_templates:
    - docker.io/twdps/{{ .ProjectName }}:latest-linux-amd64
    - docker.io/twdps/{{ .ProjectName }}:latest-linux-arm64

docker_signs:
  - cmd: cosign
    stdin: '{{ .Env.COSIGN_PWD }}'
    args: ["sign", "--key=cosign.key", "${artifact}"]
    artifacts: all