---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-master
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Release.Name }}-master.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: {{ .Values.Master.trafficPolicy.connectionPool.tcp.maxConnections }}
        connectTimeout: {{ .Values.Master.trafficPolicy.connectionPool.tcp.connectTimeout }}
        tcpKeepalive:
          time: {{ .Values.Master.trafficPolicy.connectionPool.tcp.tcpKeepalive.time }}
          interval: {{ .Values.Master.trafficPolicy.connectionPool.tcp.tcpKeepalive.interval }}
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: default
    labels:
      app: {{ .Release.Name }}
      version: {{ .Values.version }}
      role: master

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-slave
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Release.Name }}-slave.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: {{ .Values.Slave.trafficPolicy.connectionPool.tcp.maxConnections }}
        connectTimeout: {{ .Values.Slave.trafficPolicy.connectionPool.tcp.connectTimeout }}
        tcpKeepalive:
          time: {{ .Values.Slave.trafficPolicy.connectionPool.tcp.tcpKeepalive.time }}
          interval: {{ .Values.Slave.trafficPolicy.connectionPool.tcp.tcpKeepalive.interval }}
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: default
    labels:
      app: {{ .Release.Name }}
      version: {{ .Values.version }}
      role: slave
