---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-master
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    role: master
    version: {{ .Values.version }}
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: tcp-{{ .Release.Name }}
  selector:
    app: {{ .Release.Name }}
    role: master
    version: {{ .Values.version }}
