apiVersion: v2
name: demo-api-guestbook
version: 1.0.0
description: |-
  Part of the Kubernetes Guestbook example application.
  The demo-api-guestbook is responsible for the data contained
  in the backing Redis store. This includes read/write of "signers"
  and also the daily cleanup of the contents.

maintainers:
  - name: ThoughtWorks EMPC NA
    url: https://github.com/ThoughtWorks-DPS/demo-api-guestbook/charts

appVersion: 0.0.5
