# guestbook application
# helm install redis charts/redis --namespace=demo-dev --set version=v1.0.0 -f charts/redis/values-dev.yaml
# default to local, datacenter env must be specified, pull v0.0.0 from local registry
env: demo-dev
partof: demo-guestbook
version: "0.1.0"

registry: docker.io/twdps
image: demo-guestbook
replicas: 3
resources:
  requests:
    memory: "128Mi"
    cpu: "250m"

Service:
  portname: guestbook
  
Ingress:
  host: dev.twdps.digital
  gateway: istio-system/twdps-digital-dev-gateway

imagePullPolicy: Always

# helm upgrade guestbook charts/guestbook --install --namespace=demo-dev --set version=0.1.0 -f charts/guestbook/values-dev.yaml
